[package]
name = "BerlinsWeather"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.128"